// Kambaz/Database/pazza.js

// Enriched seed data with 12+ posts per course and 4-5 follow-ups each
const pazzaSeedData = {
    folders: [
        // CS5610 folders
        { _id: "5610-hw1", name: "hw1", course: "5610", isDefault: true, order: 1 },
        { _id: "5610-hw2", name: "hw2", course: "5610", isDefault: true, order: 2 },
        { _id: "5610-hw3", name: "hw3", course: "5610", isDefault: true, order: 3 },
        { _id: "5610-hw4", name: "hw4", course: "5610", isDefault: true, order: 4 },
        { _id: "5610-hw5", name: "hw5", course: "5610", isDefault: true, order: 5 },
        { _id: "5610-hw6", name: "hw6", course: "5610", isDefault: true, order: 6 },
        { _id: "5610-project", name: "project", course: "5610", isDefault: true, order: 7 },
        { _id: "5610-exam", name: "exam", course: "5610", isDefault: true, order: 8 },
        { _id: "5610-logistics", name: "logistics", course: "5610", isDefault: true, order: 9 },
        { _id: "5610-other", name: "other", course: "5610", isDefault: true, order: 10 },
        { _id: "5610-office_hours", name: "office_hours", course: "5610", isDefault: true, order: 11 },

        // CS5520 folders
        { _id: "5520-hw1", name: "hw1", course: "5520", isDefault: true, order: 1 },
        { _id: "5520-hw2", name: "hw2", course: "5520", isDefault: true, order: 2 },
        { _id: "5520-hw3", name: "hw3", course: "5520", isDefault: true, order: 3 },
        { _id: "5520-hw4", name: "hw4", course: "5520", isDefault: true, order: 4 },
        { _id: "5520-hw5", name: "hw5", course: "5520", isDefault: true, order: 5 },
        { _id: "5520-hw6", name: "hw6", course: "5520", isDefault: true, order: 6 },
        { _id: "5520-project", name: "project", course: "5520", isDefault: true, order: 7 },
        { _id: "5520-exam", name: "exam", course: "5520", isDefault: true, order: 8 },
        { _id: "5520-logistics", name: "logistics", course: "5520", isDefault: true, order: 9 },
        { _id: "5520-other", name: "other", course: "5520", isDefault: true, order: 10 },
        { _id: "5520-office_hours", name: "office_hours", course: "5520", isDefault: true, order: 11 },

        // CS5004 folders
        { _id: "5004-hw1", name: "hw1", course: "5004", isDefault: true, order: 1 },
        { _id: "5004-hw2", name: "hw2", course: "5004", isDefault: true, order: 2 },
        { _id: "5004-hw3", name: "hw3", course: "5004", isDefault: true, order: 3 },
        { _id: "5004-hw4", name: "hw4", course: "5004", isDefault: true, order: 4 },
        { _id: "5004-hw5", name: "hw5", course: "5004", isDefault: true, order: 5 },
        { _id: "5004-hw6", name: "hw6", course: "5004", isDefault: true, order: 6 },
        { _id: "5004-project", name: "project", course: "5004", isDefault: true, order: 7 },
        { _id: "5004-exam", name: "exam", course: "5004", isDefault: true, order: 8 },
        { _id: "5004-logistics", name: "logistics", course: "5004", isDefault: true, order: 9 },
        { _id: "5004-other", name: "other", course: "5004", isDefault: true, order: 10 },
        { _id: "5004-office_hours", name: "office_hours", course: "5004", isDefault: true, order: 11 },

        // CS5200 folders
        { _id: "5200-hw1", name: "hw1", course: "5200", isDefault: true, order: 1 },
        { _id: "5200-hw2", name: "hw2", course: "5200", isDefault: true, order: 2 },
        { _id: "5200-hw3", name: "hw3", course: "5200", isDefault: true, order: 3 },
        { _id: "5200-hw4", name: "hw4", course: "5200", isDefault: true, order: 4 },
        { _id: "5200-hw5", name: "hw5", course: "5200", isDefault: true, order: 5 },
        { _id: "5200-hw6", name: "hw6", course: "5200", isDefault: true, order: 6 },
        { _id: "5200-project", name: "project", course: "5200", isDefault: true, order: 7 },
        { _id: "5200-exam", name: "exam", course: "5200", isDefault: true, order: 8 },
        { _id: "5200-logistics", name: "logistics", course: "5200", isDefault: true, order: 9 },
        { _id: "5200-other", name: "other", course: "5200", isDefault: true, order: 10 },
        { _id: "5200-office_hours", name: "office_hours", course: "5200", isDefault: true, order: 11 },

        // CS5800 folders
        { _id: "5800-hw1", name: "hw1", course: "5800", isDefault: true, order: 1 },
        { _id: "5800-hw2", name: "hw2", course: "5800", isDefault: true, order: 2 },
        { _id: "5800-hw3", name: "hw3", course: "5800", isDefault: true, order: 3 },
        { _id: "5800-hw4", name: "hw4", course: "5800", isDefault: true, order: 4 },
        { _id: "5800-hw5", name: "hw5", course: "5800", isDefault: true, order: 5 },
        { _id: "5800-hw6", name: "hw6", course: "5800", isDefault: true, order: 6 },
        { _id: "5800-project", name: "project", course: "5800", isDefault: true, order: 7 },
        { _id: "5800-exam", name: "exam", course: "5800", isDefault: true, order: 8 },
        { _id: "5800-logistics", name: "logistics", course: "5800", isDefault: true, order: 9 },
        { _id: "5800-other", name: "other", course: "5800", isDefault: true, order: 10 },
        { _id: "5800-office_hours", name: "office_hours", course: "5800", isDefault: true, order: 11 },

        // CS6510 folders
        { _id: "6510-hw1", name: "hw1", course: "6510", isDefault: true, order: 1 },
        { _id: "6510-hw2", name: "hw2", course: "6510", isDefault: true, order: 2 },
        { _id: "6510-hw3", name: "hw3", course: "6510", isDefault: true, order: 3 },
        { _id: "6510-hw4", name: "hw4", course: "6510", isDefault: true, order: 4 },
        { _id: "6510-hw5", name: "hw5", course: "6510", isDefault: true, order: 5 },
        { _id: "6510-hw6", name: "hw6", course: "6510", isDefault: true, order: 6 },
        { _id: "6510-project", name: "project", course: "6510", isDefault: true, order: 7 },
        { _id: "6510-exam", name: "exam", course: "6510", isDefault: true, order: 8 },
        { _id: "6510-logistics", name: "logistics", course: "6510", isDefault: true, order: 9 },
        { _id: "6510-other", name: "other", course: "6510", isDefault: true, order: 10 },
        { _id: "6510-office_hours", name: "office_hours", course: "6510", isDefault: true, order: 11 },

        // CS6620 folders
        { _id: "6620-hw1", name: "hw1", course: "6620", isDefault: true, order: 1 },
        { _id: "6620-hw2", name: "hw2", course: "6620", isDefault: true, order: 2 },
        { _id: "6620-hw3", name: "hw3", course: "6620", isDefault: true, order: 3 },
        { _id: "6620-hw4", name: "hw4", course: "6620", isDefault: true, order: 4 },
        { _id: "6620-hw5", name: "hw5", course: "6620", isDefault: true, order: 5 },
        { _id: "6620-hw6", name: "hw6", course: "6620", isDefault: true, order: 6 },
        { _id: "6620-project", name: "project", course: "6620", isDefault: true, order: 7 },
        { _id: "6620-exam", name: "exam", course: "6620", isDefault: true, order: 8 },
        { _id: "6620-logistics", name: "logistics", course: "6620", isDefault: true, order: 9 },
        { _id: "6620-other", name: "other", course: "6620", isDefault: true, order: 10 },
        { _id: "6620-office_hours", name: "office_hours", course: "6620", isDefault: true, order: 11 },
    ],

    posts: [
        // ========== CS5610 Web Development Posts (13 posts) ==========
        {
            _id: "5610-post-1",
            course: "5610",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["office_hours"],
            summary: "Meet Your TA for Web Development - Pramod",
            details: "<p>Hi Everyone,</p><p>My name is Pramod, and I am excited to be your Teaching Assistant this semester. I took this course in Fall 2023 and gained valuable insights and hands-on experience, which I look forward to sharing with you all.</p><p>A little about me: I am currently pursuing my Master's in Computer Science at Northeastern University. My passion for web development has grown over the years, and I have worked on several projects utilizing technologies like React, Node.js, HTML, CSS, and MongoDB.</p>",
            author: "674e52d09a4e696e37024893",
            authorRole: "TA",
            authorName: "Pramod Kumar",
            views: 187,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            isInstructorEndorsed: true,
            createdAt: "2025-01-09T14:30:00",
            updatedAt: "2025-01-09T14:30:00"
        },
        {
            _id: "5610-post-2",
            course: "5610",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "Starting HW2",
            details: "<p>Hi! I want to start assignment 2, but don't want to effect assignment 1. For assignment 1 I submitted a link with a1-- a directory.</p><p>Should I create a new branch or just add files in the same repo?</p>",
            author: "student1",
            authorRole: "STUDENT",
            authorName: "Alice Johnson",
            views: 145,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-10T16:45:00",
            updatedAt: "2025-01-10T17:30:00"
        },
        {
            _id: "5610-post-3",
            course: "5610",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "Clarification on Lab1",
            details: "<p>In the anchor tag part of lab1 (bottom of page 17), we are asked to 'Create another link to your code repository on GitHub'</p><p>What is the difference between this and 'Create a link to your source code on GitHub'?</p>",
            author: "student2",
            authorRole: "STUDENT",
            authorName: "Bob Smith",
            views: 132,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-08T14:09:00",
            updatedAt: "2025-01-08T14:43:00"
        },
        {
            _id: "5610-post-4",
            course: "5610",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "How to make buttons sit on the right or left?",
            details: "<p>In Homework one, we are implementing an assignment editor page. At the bottom of the page, we need to create two buttons that align differently.</p><p>How can I make one button align to the left and another to the right?</p>",
            author: "student3",
            authorRole: "STUDENT",
            authorName: "Carol Davis",
            views: 98,
            hasInstructorAnswer: false,
            hasStudentAnswer: true,
            createdAt: "2025-01-09T16:09:00",
            updatedAt: "2025-01-09T16:25:00"
        },
        {
            _id: "5610-post-5",
            course: "5610",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Midterm Review Session - Friday 7pm",
            details: "<p>Dear Students,</p><p>We will be holding a midterm review session this Friday at 7pm EST in the regular classroom. We'll go over key concepts including:</p><ul><li>React Hooks</li><li>Redux state management</li><li>RESTful API design</li><li>MongoDB operations</li></ul>",
            author: "674e52d09a4e696e37024890",
            authorRole: "FACULTY",
            authorName: "Prof. Jose Annunziato",
            views: 256,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-07T10:00:00",
            updatedAt: "2025-01-07T10:00:00"
        },
        {
            _id: "5610-post-6",
            course: "5610",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Final Project Team Formation",
            details: "<p>Hi everyone! I'm looking for 2-3 teammates for the final project. I'm interested in building a social media platform.</p><p>My skills: React, TypeScript, Node.js, MongoDB</p>",
            author: "student4",
            authorRole: "STUDENT",
            authorName: "Eve Wilson",
            views: 167,
            hasInstructorAnswer: false,
            hasStudentAnswer: true,
            isInstructorEndorsed: true,
            createdAt: "2025-01-06T13:20:00",
            updatedAt: "2025-01-06T14:15:00"
        },
        {
            _id: "5610-post-7",
            course: "5610",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "Office hours moved to Thursday this week",
            details: "<p>Quick heads up: office hours are moved to <b>Thu 4–6pm</b> for this week only.</p>",
            author: "674e52d09a4e696e37024890",
            authorRole: "FACULTY",
            authorName: "Prof. Jose Annunziato",
            views: 120,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: false,
            createdAt: "2025-01-11T09:00:00",
            updatedAt: "2025-01-11T09:00:00"
        },
        {
            _id: "5610-post-8",
            course: "5610",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "Where to place Redux store in Next.js app?",
            details: "<p>Should the Redux store live in <code>app/store.ts</code> or inside the course folder?</p>",
            author: "student10",
            authorRole: "STUDENT",
            authorName: "Kelly Anderson",
            views: 89,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T13:10:00",
            updatedAt: "2025-01-11T13:40:00"
        },
        {
            _id: "5610-post-9",
            course: "5610",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "API design: plural nouns vs resources with IDs?",
            details: "<p>For REST, should I use <code>/api/courses</code> and <code>/api/courses/:id</code>? Any naming tips?</p>",
            author: "student11",
            authorRole: "STUDENT",
            authorName: "Laura Martinez",
            views: 151,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-12T10:05:00",
            updatedAt: "2025-01-12T11:12:00"
        },
        {
            _id: "5610-post-10",
            course: "5610",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Midterm coverage update",
            details: "<p>Midterm includes React Hooks, Redux Toolkit thunks, and Mongo basics. No GraphQL.</p>",
            author: "674e52d09a4e696e37024890",
            authorRole: "FACULTY",
            authorName: "Prof. Jose Annunziato",
            views: 276,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-12T18:20:00",
            updatedAt: "2025-01-12T18:20:00"
        },
        {
            _id: "5610-post-11",
            course: "5610",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "Bootstrap grid vs CSS grid for layout?",
            details: "<p>Which should I use for the dashboard layout to match the rubric?</p>",
            author: "student12",
            authorRole: "STUDENT",
            authorName: "Mei Lin",
            views: 79,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-13T09:35:00",
            updatedAt: "2025-01-13T10:02:00"
        },
        {
            _id: "5610-post-12",
            course: "5610",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["office_hours"],
            summary: "Can we use NextAuth for login?",
            details: "<p>Is NextAuth allowed for authentication, or should we stick to sessions only?</p>",
            author: "student13",
            authorRole: "STUDENT",
            authorName: "Noah Patel",
            views: 97,
            hasInstructorAnswer: false,
            hasStudentAnswer: true,
            createdAt: "2025-01-13T14:00:00",
            updatedAt: "2025-01-13T14:20:00"
        },
        {
            _id: "5610-post-13",
            course: "5610",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Sample MERN repo link for reference",
            details: "<p>Here's a reference MERN repo with Redux Toolkit examples you can browse: github.com/example/mern-starter</p>",
            author: "674e52d09a4e696e37024893",
            authorRole: "TA",
            authorName: "Pramod Kumar",
            views: 188,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-14T08:40:00",
            updatedAt: "2025-01-14T08:40:00"
        },

        // ========== CS5520 Mobile App Development Posts (12 posts) ==========
        {
            _id: "5520-post-1",
            course: "5520",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "React Native vs Flutter for Final Project?",
            details: "<p>For the final project, are we required to use React Native, or can we choose Flutter?</p><p>I have more experience with Flutter and feel I could build something more polished.</p>",
            author: "student5",
            authorRole: "STUDENT",
            authorName: "Frank Martinez",
            views: 142,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-10T11:00:00",
            updatedAt: "2025-01-10T11:45:00"
        },
        {
            _id: "5520-post-2",
            course: "5520",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "Expo camera permissions not working on iOS",
            details: "<p>I'm trying to implement the camera feature for HW2, but when I run the app on my iPhone, it crashes when requesting camera permissions.</p>",
            author: "student6",
            authorRole: "STUDENT",
            authorName: "Grace Lee",
            views: 138,
            hasInstructorAnswer: false,
            hasStudentAnswer: true,
            createdAt: "2025-01-09T15:30:00",
            updatedAt: "2025-01-09T16:00:00"
        },
        {
            _id: "5520-post-3",
            course: "5520",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "Class Cancelled Next Tuesday - University Holiday",
            details: "<p>Hi Everyone,</p><p>Just a reminder that class next Tuesday (Jan 16) is cancelled due to the university holiday.</p>",
            author: "instructor2",
            authorRole: "FACULTY",
            authorName: "Dr. Mike Johnson",
            views: 193,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-08T09:00:00",
            updatedAt: "2025-01-08T09:00:00"
        },
        {
            _id: "5520-post-4",
            course: "5520",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "HW2 emulator setup checklist (Android & iOS)",
            details: "<p>Follow this checklist to avoid common Expo issues on first run.</p>",
            author: "instructor2",
            authorRole: "FACULTY",
            authorName: "Dr. Mike Johnson",
            views: 202,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T10:10:00",
            updatedAt: "2025-01-11T10:10:00"
        },
        {
            _id: "5520-post-5",
            course: "5520",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "FlatList keyExtractor best practice?",
            details: "<p>Is using the array index OK, or must we use a stable id?</p>",
            author: "student12",
            authorRole: "STUDENT",
            authorName: "Mei Lin",
            views: 84,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T16:25:00",
            updatedAt: "2025-01-11T17:00:00"
        },
        {
            _id: "5520-post-6",
            course: "5520",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "React Navigation: stack vs tab for HW1?",
            details: "<p>Do we need both Stack and Bottom Tabs, or just one is fine?</p>",
            author: "student6",
            authorRole: "STUDENT",
            authorName: "Grace Lee",
            views: 78,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-12T09:30:00",
            updatedAt: "2025-01-12T10:12:00"
        },
        {
            _id: "5520-post-7",
            course: "5520",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Quiz 1 topics",
            details: "<p>Quiz 1 will cover components, state, props, and React Navigation basics.</p>",
            author: "instructor2",
            authorRole: "FACULTY",
            authorName: "Dr. Mike Johnson",
            views: 241,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-12T18:00:00",
            updatedAt: "2025-01-12T18:00:00"
        },
        {
            _id: "5520-post-8",
            course: "5520",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Expo push notifications quota?",
            details: "<p>Any limits we should worry about for the final app?</p>",
            author: "student14",
            authorRole: "STUDENT",
            authorName: "Owen Zhang",
            views: 72,
            hasInstructorAnswer: false,
            hasStudentAnswer: true,
            createdAt: "2025-01-13T12:40:00",
            updatedAt: "2025-01-13T12:55:00"
        },
        {
            _id: "5520-post-9",
            course: "5520",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw3"],
            summary: "Image picker permissions on Android 14",
            details: "<p>Getting a <code>READ_MEDIA_IMAGES</code> error—any quick fix?</p>",
            author: "student5",
            authorRole: "STUDENT",
            authorName: "Frank Martinez",
            views: 86,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-14T08:10:00",
            updatedAt: "2025-01-14T08:30:00"
        },
        {
            _id: "5520-post-10",
            course: "5520",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["office_hours"],
            summary: "TA code review slots posted",
            details: "<p>Sign up for 20-min code review slots this week via the shared sheet.</p>",
            author: "ta1",
            authorRole: "TA",
            authorName: "Sarah Chen",
            views: 107,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-14T15:45:00",
            updatedAt: "2025-01-14T15:45:00"
        },
        {
            _id: "5520-post-11",
            course: "5520",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw4"],
            summary: "AsyncStorage vs SecureStore for sensitive data?",
            details: "<p>Should we use Expo SecureStore for storing API keys in HW4, or is AsyncStorage sufficient for this assignment?</p>",
            author: "student15",
            authorRole: "STUDENT",
            authorName: "Rachel Kim",
            views: 93,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T10:20:00",
            updatedAt: "2025-01-15T11:00:00"
        },
        {
            _id: "5520-post-12",
            course: "5520",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Firebase vs AWS Amplify for backend?",
            details: "<p>For the final project backend, which would you recommend? I need auth, database, and file storage.</p>",
            author: "student16",
            authorRole: "STUDENT",
            authorName: "Tom Wilson",
            views: 115,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-15T14:30:00",
            updatedAt: "2025-01-15T15:45:00"
        },

        // ========== CS5004 Object-Oriented Design Posts (12 posts) ==========
        {
            _id: "5004-post-1",
            course: "5004",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "Difference between Composition and Aggregation?",
            details: "<p>I'm working on the HW2 design diagrams and confused about when to use composition vs aggregation relationships in UML.</p>",
            author: "student7",
            authorRole: "STUDENT",
            authorName: "Helen Brown",
            views: 148,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-10T13:00:00",
            updatedAt: "2025-01-10T14:30:00"
        },
        {
            _id: "5004-post-2",
            course: "5004",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "Welcome to CS5004 - Object-Oriented Design",
            details: "<p>Welcome to CS5004! This course will cover fundamental OOP concepts using Java. Please make sure you have JDK 17 installed.</p>",
            author: "instructor3",
            authorRole: "FACULTY",
            authorName: "Dr. Sarah Chen",
            views: 412,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-10T08:00:00",
            updatedAt: "2025-01-10T08:00:00"
        },
        {
            _id: "5004-post-3",
            course: "5004",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "Interfaces vs abstract classes in Java?",
            details: "<p>Which is preferred for HW1 shapes hierarchy?</p>",
            author: "student15",
            authorRole: "STUDENT",
            authorName: "Priya Singh",
            views: 91,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T11:15:00",
            updatedAt: "2025-01-11T11:45:00"
        },
        {
            _id: "5004-post-4",
            course: "5004",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "JDK 17 installation tips (Mac/Windows)",
            details: "<p>Here are common fixes for PATH and JAVA_HOME issues.</p>",
            author: "instructor3",
            authorRole: "FACULTY",
            authorName: "Dr. Sarah Chen",
            views: 198,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T13:40:00",
            updatedAt: "2025-01-11T13:40:00"
        },
        {
            _id: "5004-post-5",
            course: "5004",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "UML association vs aggregation example",
            details: "<p>Is <i>Order</i>–<i>OrderItem</i> aggregation or composition?</p>",
            author: "student7",
            authorRole: "STUDENT",
            authorName: "Helen Brown",
            views: 94,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-12T10:30:00",
            updatedAt: "2025-01-12T11:05:00"
        },
        {
            _id: "5004-post-6",
            course: "5004",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Exam 1 practice set released",
            details: "<p>Includes inheritance, polymorphism, and SOLID questions.</p>",
            author: "instructor3",
            authorRole: "FACULTY",
            authorName: "Dr. Sarah Chen",
            views: 250,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-12T19:00:00",
            updatedAt: "2025-01-12T19:00:00"
        },
        {
            _id: "5004-post-7",
            course: "5004",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Project idea: library system — scope OK?",
            details: "<p>Thinking of a library system with borrowing, holds, and fines. Too big?</p>",
            author: "student16",
            authorRole: "STUDENT",
            authorName: "David Park",
            views: 76,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-13T09:05:00",
            updatedAt: "2025-01-13T09:45:00"
        },
        {
            _id: "5004-post-8",
            course: "5004",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw3"],
            summary: "Unit testing with JUnit 5 setup",
            details: "<p>Any template for setting up parameterized tests?</p>",
            author: "student17",
            authorRole: "STUDENT",
            authorName: "Ivy Nguyen",
            views: 83,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-13T14:25:00",
            updatedAt: "2025-01-13T14:50:00"
        },
        {
            _id: "5004-post-9",
            course: "5004",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["office_hours"],
            summary: "TA office hours extended for HW2",
            details: "<p>Extra hour on Friday to help with UML diagrams.</p>",
            author: "ta2",
            authorRole: "TA",
            authorName: "Alex Rivera",
            views: 121,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-14T12:10:00",
            updatedAt: "2025-01-14T12:10:00"
        },
        {
            _id: "5004-post-10",
            course: "5004",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw4"],
            summary: "Factory pattern vs Builder pattern?",
            details: "<p>For HW4's design patterns section, when should I use Factory vs Builder? They seem similar.</p>",
            author: "student18",
            authorRole: "STUDENT",
            authorName: "Kevin Liu",
            views: 105,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T09:15:00",
            updatedAt: "2025-01-15T10:30:00"
        },
        {
            _id: "5004-post-11",
            course: "5004",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw5"],
            summary: "Observer pattern implementation in Java",
            details: "<p>Should we use Java's built-in Observer interface or implement our own for HW5?</p>",
            author: "student19",
            authorRole: "STUDENT",
            authorName: "Lisa Wang",
            views: 89,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-15T11:45:00",
            updatedAt: "2025-01-15T12:30:00"
        },
        {
            _id: "5004-post-12",
            course: "5004",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "MVC pattern for final project?",
            details: "<p>Is MVC required for the final project, or can we use other architectural patterns like MVP or MVVM?</p>",
            author: "student20",
            authorRole: "STUDENT",
            authorName: "Marcus Chen",
            views: 112,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T15:00:00",
            updatedAt: "2025-01-15T16:15:00"
        },

        // ========== CS5200 Database Management Systems Posts (12 posts) ==========
        {
            _id: "5200-post-1",
            course: "5200",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "Welcome to CS5200 — DBMS overview",
            details: "<p>Please install PostgreSQL 15 and pgAdmin before next class.</p>",
            author: "instructor4",
            authorRole: "FACULTY",
            authorName: "Dr. Lina Gomez",
            views: 312,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-07T08:00:00",
            updatedAt: "2025-01-07T08:00:00"
        },
        {
            _id: "5200-post-2",
            course: "5200",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "Difference between primary key and unique constraint?",
            details: "<p>In Postgres, when should I prefer one over the other?</p>",
            author: "student18",
            authorRole: "STUDENT",
            authorName: "Mohammed Ali",
            views: 158,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-08T11:40:00",
            updatedAt: "2025-01-08T12:05:00"
        },
        {
            _id: "5200-post-3",
            course: "5200",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "Best way to model many-to-many in SQL?",
            details: "<p>Is a join table always the right way?</p>",
            author: "student19",
            authorRole: "STUDENT",
            authorName: "Sofia Rossi",
            views: 146,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-09T10:15:00",
            updatedAt: "2025-01-09T10:50:00"
        },
        {
            _id: "5200-post-4",
            course: "5200",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Midterm will include SQL window functions",
            details: "<p>Study <code>ROW_NUMBER</code>, <code>RANK</code>, and <code>PARTITION BY</code>.</p>",
            author: "instructor4",
            authorRole: "FACULTY",
            authorName: "Dr. Lina Gomez",
            views: 228,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-10T09:00:00",
            updatedAt: "2025-01-10T09:00:00"
        },
        {
            _id: "5200-post-5",
            course: "5200",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Project idea feedback: movie ratings DB",
            details: "<p>Planning a schema for users, movies, ratings, and tags. Suggestions?</p>",
            author: "student20",
            authorRole: "STUDENT",
            authorName: "Elena Petrova",
            views: 87,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T13:50:00",
            updatedAt: "2025-01-11T14:10:00"
        },
        {
            _id: "5200-post-6",
            course: "5200",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw3"],
            summary: "Normalization vs performance trade-offs",
            details: "<p>When is denormalization acceptable in this course?</p>",
            author: "student21",
            authorRole: "STUDENT",
            authorName: "Jason Miller",
            views: 91,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-12T16:05:00",
            updatedAt: "2025-01-12T16:40:00"
        },
        {
            _id: "5200-post-7",
            course: "5200",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["office_hours"],
            summary: "ER diagram help session Friday",
            details: "<p>Bring your ERDs for quick feedback before HW2 is due.</p>",
            author: "ta3",
            authorRole: "TA",
            authorName: "Ravi Sharma",
            views: 113,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-13T10:20:00",
            updatedAt: "2025-01-13T10:20:00"
        },
        {
            _id: "5200-post-8",
            course: "5200",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw4"],
            summary: "Indexing strategy for large tables?",
            details: "<p>My query on the orders table (1M rows) is slow. Should I add composite indexes or partition the table?</p>",
            author: "student22",
            authorRole: "STUDENT",
            authorName: "Nina Patel",
            views: 124,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-14T10:30:00",
            updatedAt: "2025-01-14T11:45:00"
        },
        {
            _id: "5200-post-9",
            course: "5200",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw5"],
            summary: "Transaction isolation levels confusion",
            details: "<p>Can someone explain the difference between READ COMMITTED and REPEATABLE READ with an example?</p>",
            author: "student23",
            authorRole: "STUDENT",
            authorName: "Oliver Zhang",
            views: 98,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-14T14:20:00",
            updatedAt: "2025-01-14T15:00:00"
        },
        {
            _id: "5200-post-10",
            course: "5200",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "NoSQL vs SQL for social media project?",
            details: "<p>Building a Twitter-like app. Should I use MongoDB for flexibility or stick with PostgreSQL?</p>",
            author: "student24",
            authorRole: "STUDENT",
            authorName: "Patricia Lee",
            views: 135,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-15T09:00:00",
            updatedAt: "2025-01-15T10:15:00"
        },
        {
            _id: "5200-post-11",
            course: "5200",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Practice exam solutions posted",
            details: "<p>Solutions for the practice midterm are now available on Canvas. Review carefully!</p>",
            author: "instructor4",
            authorRole: "FACULTY",
            authorName: "Dr. Lina Gomez",
            views: 245,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-15T12:00:00",
            updatedAt: "2025-01-15T12:00:00"
        },
        {
            _id: "5200-post-12",
            course: "5200",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw6"],
            summary: "Stored procedures vs application logic?",
            details: "<p>For HW6's business logic, should we implement it in stored procedures or keep it in the application layer?</p>",
            author: "student25",
            authorRole: "STUDENT",
            authorName: "Quinn Roberts",
            views: 102,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T16:30:00",
            updatedAt: "2025-01-15T17:00:00"
        },

        // ========== CS5800 Algorithms Posts (12 posts) ==========
        {
            _id: "5800-post-1",
            course: "5800",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "Problem set policy reminder",
            details: "<p>Work in pairs is allowed, but submit your own write-up.</p>",
            author: "instructor5",
            authorRole: "FACULTY",
            authorName: "Dr. Ethan Brooks",
            views: 290,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-07T09:00:00",
            updatedAt: "2025-01-07T09:00:00"
        },
        {
            _id: "5800-post-2",
            course: "5800",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "Proof by induction vs loop invariant",
            details: "<p>When proving correctness of algorithms, how do we decide which to use?</p>",
            author: "student22",
            authorRole: "STUDENT",
            authorName: "Hannah Kim",
            views: 172,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-08T14:30:00",
            updatedAt: "2025-01-08T15:05:00"
        },
        {
            _id: "5800-post-3",
            course: "5800",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "Master theorem case 2 confusion",
            details: "<p>How do we verify the regularity condition properly?</p>",
            author: "student23",
            authorRole: "STUDENT",
            authorName: "Leo Garcia",
            views: 155,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-09T11:00:00",
            updatedAt: "2025-01-09T11:35:00"
        },
        {
            _id: "5800-post-4",
            course: "5800",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Midterm focuses on recurrences & graphs",
            details: "<p>Expect DFS/BFS, shortest paths basics, and asymptotics practice.</p>",
            author: "instructor5",
            authorRole: "FACULTY",
            authorName: "Dr. Ethan Brooks",
            views: 233,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-10T18:10:00",
            updatedAt: "2025-01-10T18:10:00"
        },
        {
            _id: "5800-post-5",
            course: "5800",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Project idea: comparing heap variants",
            details: "<p>Thinking of benchmarking binary heap vs pairing heap—sound good?</p>",
            author: "student24",
            authorRole: "STUDENT",
            authorName: "Marta Silva",
            views: 80,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T12:20:00",
            updatedAt: "2025-01-11T12:45:00"
        },
        {
            _id: "5800-post-6",
            course: "5800",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw3"],
            summary: "When is Dijkstra incorrect?",
            details: "<p>Looking for a simple counter-example with negative edges.</p>",
            author: "student25",
            authorRole: "STUDENT",
            authorName: "Arjun Rao",
            views: 148,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-12T10:40:00",
            updatedAt: "2025-01-12T11:05:00"
        },
        {
            _id: "5800-post-7",
            course: "5800",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["office_hours"],
            summary: "Graph proofs clinic",
            details: "<p>Bring your MST and shortest path proofs—TA will review common gaps.</p>",
            author: "ta4",
            authorRole: "TA",
            authorName: "Nina Alvarez",
            views: 109,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-13T16:30:00",
            updatedAt: "2025-01-13T16:30:00"
        },
        {
            _id: "5800-post-8",
            course: "5800",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw4"],
            summary: "Dynamic programming vs greedy approach",
            details: "<p>For the knapsack problem in HW4, why doesn't the greedy approach work? I get the right answer sometimes.</p>",
            author: "student26",
            authorRole: "STUDENT",
            authorName: "Robert Chen",
            views: 126,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-14T09:45:00",
            updatedAt: "2025-01-14T10:30:00"
        },
        {
            _id: "5800-post-9",
            course: "5800",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw5"],
            summary: "NP-completeness reduction direction",
            details: "<p>To prove X is NP-complete, do we reduce FROM a known NP-complete problem TO X, or the other way?</p>",
            author: "student27",
            authorRole: "STUDENT",
            authorName: "Samantha Wu",
            views: 117,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-14T13:00:00",
            updatedAt: "2025-01-14T14:15:00"
        },
        {
            _id: "5800-post-10",
            course: "5800",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Parallel algorithms for project?",
            details: "<p>Can we implement parallel versions of sorting algorithms for extra credit?</p>",
            author: "student28",
            authorRole: "STUDENT",
            authorName: "Tyler Johnson",
            views: 95,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T10:00:00",
            updatedAt: "2025-01-15T11:00:00"
        },
        {
            _id: "5800-post-11",
            course: "5800",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Final exam comprehensive",
            details: "<p>The final will cover all topics. Focus on: complexity analysis, graph algorithms, DP, and NP-completeness.</p>",
            author: "instructor5",
            authorRole: "FACULTY",
            authorName: "Dr. Ethan Brooks",
            views: 267,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-15T14:00:00",
            updatedAt: "2025-01-15T14:00:00"
        },
        {
            _id: "5800-post-12",
            course: "5800",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw6"],
            summary: "Approximation algorithms ratio",
            details: "<p>How do we prove the 2-approximation ratio for the vertex cover algorithm in HW6?</p>",
            author: "student29",
            authorRole: "STUDENT",
            authorName: "Uma Patel",
            views: 88,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T16:00:00",
            updatedAt: "2025-01-15T17:15:00"
        },

        // ========== CS6510 Advanced Software Development Posts (12 posts) ==========
        {
            _id: "6510-post-1",
            course: "6510",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "Tooling stack for the course",
            details: "<p>We'll use TypeScript, Jest, and GitHub Actions. Please enable CI on your repo.</p>",
            author: "instructor6",
            authorRole: "FACULTY",
            authorName: "Dr. Olivia Reed",
            views: 275,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-07T08:30:00",
            updatedAt: "2025-01-07T08:30:00"
        },
        {
            _id: "6510-post-2",
            course: "6510",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "Clean architecture layers naming",
            details: "<p>Is <i>application</i> vs <i>domain</i> naming important for grading?</p>",
            author: "student26",
            authorRole: "STUDENT",
            authorName: "Zara Ahmed",
            views: 140,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-08T12:10:00",
            updatedAt: "2025-01-08T12:40:00"
        },
        {
            _id: "6510-post-3",
            course: "6510",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Monorepo vs polyrepo for capstone",
            details: "<p>Team of 4—monorepo with Nx or separate services?</p>",
            author: "student27",
            authorRole: "STUDENT",
            authorName: "Ben Cooper",
            views: 133,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-09T09:20:00",
            updatedAt: "2025-01-09T09:55:00"
        },
        {
            _id: "6510-post-4",
            course: "6510",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Midterm rubric posted",
            details: "<p>Focus on testing pyramid and CI/CD pipelines. Short essay and MCQ.</p>",
            author: "instructor6",
            authorRole: "FACULTY",
            authorName: "Dr. Olivia Reed",
            views: 216,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-10T10:00:00",
            updatedAt: "2025-01-10T10:00:00"
        },
        {
            _id: "6510-post-5",
            course: "6510",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "Testing async services with Jest",
            details: "<p>Recommended pattern for mocking fetch/axios?</p>",
            author: "student28",
            authorRole: "STUDENT",
            authorName: "Chris Young",
            views: 89,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T15:00:00",
            updatedAt: "2025-01-11T15:30:00"
        },
        {
            _id: "6510-post-6",
            course: "6510",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw3"],
            summary: "Feature flags in production",
            details: "<p>Can we demo LaunchDarkly style flags locally?</p>",
            author: "student29",
            authorRole: "STUDENT",
            authorName: "Diego Alvarez",
            views: 77,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-12T13:40:00",
            updatedAt: "2025-01-12T14:05:00"
        },
        {
            _id: "6510-post-7",
            course: "6510",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["office_hours"],
            summary: "Design review slots available",
            details: "<p>Book a 25-min slot to review your architecture diagrams.</p>",
            author: "ta5",
            authorRole: "TA",
            authorName: "Jasmine Lee",
            views: 98,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-13T11:25:00",
            updatedAt: "2025-01-13T11:25:00"
        },
        {
            _id: "6510-post-8",
            course: "6510",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw4"],
            summary: "Microservices communication patterns",
            details: "<p>For HW4, should we use REST, gRPC, or message queues for service-to-service communication?</p>",
            author: "student30",
            authorRole: "STUDENT",
            authorName: "Victoria Brown",
            views: 112,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-14T08:30:00",
            updatedAt: "2025-01-14T09:45:00"
        },
        {
            _id: "6510-post-9",
            course: "6510",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw5"],
            summary: "Docker compose vs Kubernetes for HW5?",
            details: "<p>The assignment mentions container orchestration. Is Docker Compose sufficient or do we need K8s?</p>",
            author: "student31",
            authorRole: "STUDENT",
            authorName: "William Davis",
            views: 124,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-14T12:00:00",
            updatedAt: "2025-01-14T13:30:00"
        },
        {
            _id: "6510-post-10",
            course: "6510",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Event sourcing implementation",
            details: "<p>Our team wants to implement event sourcing. Any recommended libraries or patterns for TypeScript?</p>",
            author: "student32",
            authorRole: "STUDENT",
            authorName: "Xavier Martinez",
            views: 97,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T09:30:00",
            updatedAt: "2025-01-15T10:45:00"
        },
        {
            _id: "6510-post-11",
            course: "6510",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "System design interview practice",
            details: "<p>We'll run mock system design interviews next week. Sign up for 45-minute slots on Canvas.</p>",
            author: "instructor6",
            authorRole: "FACULTY",
            authorName: "Dr. Olivia Reed",
            views: 189,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T13:00:00",
            updatedAt: "2025-01-15T13:00:00"
        },
        {
            _id: "6510-post-12",
            course: "6510",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw6"],
            summary: "CQRS pattern with event store",
            details: "<p>Implementing CQRS for HW6. Should read models be eventually consistent or strongly consistent?</p>",
            author: "student33",
            authorRole: "STUDENT",
            authorName: "Yara Thompson",
            views: 83,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T15:30:00",
            updatedAt: "2025-01-15T16:45:00"
        },

        // ========== CS6620 Cloud Computing Posts (12 posts) ==========
        {
            _id: "6620-post-1",
            course: "6620",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["logistics"],
            summary: "Cloud accounts & credits",
            details: "<p>Activate your AWS Educate credits and set budgets/alerts before HW1.</p>",
            author: "instructor7",
            authorRole: "FACULTY",
            authorName: "Dr. Victor Huang",
            views: 305,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            isPinned: true,
            createdAt: "2025-01-07T08:15:00",
            updatedAt: "2025-01-07T08:15:00"
        },
        {
            _id: "6620-post-2",
            course: "6620",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw1"],
            summary: "IAM roles vs policies confusion",
            details: "<p>Do we attach policies to roles or users for HW1 EC2 access?</p>",
            author: "student30",
            authorRole: "STUDENT",
            authorName: "Fiona Wu",
            views: 162,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-08T12:50:00",
            updatedAt: "2025-01-08T13:20:00"
        },
        {
            _id: "6620-post-3",
            course: "6620",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw2"],
            summary: "S3 static site with CloudFront caching",
            details: "<p>My updates are delayed—how to invalidate efficiently?</p>",
            author: "student31",
            authorRole: "STUDENT",
            authorName: "George Li",
            views: 144,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-09T10:35:00",
            updatedAt: "2025-01-09T11:05:00"
        },
        {
            _id: "6620-post-4",
            course: "6620",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "Midterm topics: IAM, S3, EC2 basics, VPC",
            details: "<p>Focus on networking fundamentals and cost awareness.</p>",
            author: "instructor7",
            authorRole: "FACULTY",
            authorName: "Dr. Victor Huang",
            views: 221,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-10T17:10:00",
            updatedAt: "2025-01-10T17:10:00"
        },
        {
            _id: "6620-post-5",
            course: "6620",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Kubernetes or ECS for final project?",
            details: "<p>Team experience varies—what's safer for the demo?</p>",
            author: "student32",
            authorRole: "STUDENT",
            authorName: "Harper Johnson",
            views: 139,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-11T12:05:00",
            updatedAt: "2025-01-11T12:30:00"
        },
        {
            _id: "6620-post-6",
            course: "6620",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw3"],
            summary: "VPC peering vs Transit Gateway",
            details: "<p>Which should we use in the assignment architecture?</p>",
            author: "student33",
            authorRole: "STUDENT",
            authorName: "Isabella Rossi",
            views: 133,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-12T09:55:00",
            updatedAt: "2025-01-12T10:25:00"
        },
        {
            _id: "6620-post-7",
            course: "6620",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["office_hours"],
            summary: "AWS billing alarms workshop",
            details: "<p>We'll set up cost and usage alarms together—bring your laptops.</p>",
            author: "ta6",
            authorRole: "TA",
            authorName: "Samantha Cho",
            views: 152,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-13T15:00:00",
            updatedAt: "2025-01-13T15:00:00"
        },
        {
            _id: "6620-post-8",
            course: "6620",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw4"],
            summary: "Lambda cold start optimization",
            details: "<p>My Lambda function has 5-second cold starts. Is provisioned concurrency worth the cost for HW4?</p>",
            author: "student34",
            authorRole: "STUDENT",
            authorName: "Zachary Nelson",
            views: 118,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-14T10:00:00",
            updatedAt: "2025-01-14T11:15:00"
        },
        {
            _id: "6620-post-9",
            course: "6620",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw5"],
            summary: "DynamoDB vs RDS for serverless app",
            details: "<p>Building a serverless app for HW5. DynamoDB seems complex—can we use RDS Proxy with Lambda instead?</p>",
            author: "student35",
            authorRole: "STUDENT",
            authorName: "Amy Chen",
            views: 126,
            hasInstructorAnswer: true,
            hasStudentAnswer: true,
            createdAt: "2025-01-14T14:00:00",
            updatedAt: "2025-01-14T15:30:00"
        },
        {
            _id: "6620-post-10",
            course: "6620",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["project"],
            summary: "Multi-region deployment strategy",
            details: "<p>Our project requires multi-region. Should we use Route 53 with health checks or AWS Global Accelerator?</p>",
            author: "student36",
            authorRole: "STUDENT",
            authorName: "Brian Wilson",
            views: 108,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T08:45:00",
            updatedAt: "2025-01-15T10:00:00"
        },
        {
            _id: "6620-post-11",
            course: "6620",
            type: "note",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["exam"],
            summary: "AWS certification prep resources",
            details: "<p>For those interested in AWS certification after the course, I've compiled practice questions and study guides.</p>",
            author: "instructor7",
            authorRole: "FACULTY",
            authorName: "Dr. Victor Huang",
            views: 234,
            hasInstructorAnswer: false,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T12:30:00",
            updatedAt: "2025-01-15T12:30:00"
        },
        {
            _id: "6620-post-12",
            course: "6620",
            type: "question",
            postTo: "entire_class",
            visibleTo: [],
            folders: ["hw6"],
            summary: "Step Functions vs SQS/SNS for workflow",
            details: "<p>HW6 requires a complex workflow. Step Functions seem overkill—can we just chain Lambda with SQS?</p>",
            author: "student37",
            authorRole: "STUDENT",
            authorName: "Catherine Park",
            views: 94,
            hasInstructorAnswer: true,
            hasStudentAnswer: false,
            createdAt: "2025-01-15T17:00:00",
            updatedAt: "2025-01-15T17:45:00"
        }
    ],

    // Comprehensive answers collection
    answers: [
        // CS5610 answers
        {
            _id: "answer-5610-1",
            postId: "5610-post-2",
            content: "<p>Hi! I recommend creating a new branch for each assignment. This keeps your work organized and makes it easy to switch between assignments. Use <code>git checkout -b hw2</code> to create a new branch.</p>",
            author: "674e52d09a4e696e37024890",
            authorRole: "FACULTY",
            authorName: "Prof. Jose Annunziato",
            createdAt: "2025-01-10T17:30:00"
        },
        {
            _id: "answer-5610-2",
            postId: "5610-post-3",
            content: "<p>It's the same repository. Just add another link to your GitHub repo - they want to see multiple ways to link to the same resource. One can be a text link, another can be an image link.</p>",
            author: "674e52d09a4e696e37024893",
            authorRole: "TA",
            authorName: "Pramod Kumar",
            createdAt: "2025-01-08T14:43:00"
        },
        {
            _id: "answer-5610-3",
            postId: "5610-post-4",
            content: "<p>You can use CSS flexbox! Add <code>display: flex; justify-content: space-between;</code> to the container div. This will push one button to the left and one to the right.</p>",
            author: "student8",
            authorRole: "STUDENT",
            authorName: "Ian Rodriguez",
            createdAt: "2025-01-09T16:25:00"
        },
        {
            _id: "answer-5610-4",
            postId: "5610-post-6",
            content: "<p>I'm interested! I have experience with React and Node.js. Let's connect after class. We can build something amazing!</p>",
            author: "student9",
            authorRole: "STUDENT",
            authorName: "Jack Wilson",
            createdAt: "2025-01-06T14:15:00"
        },
        {
            _id: "answer-5610-5",
            postId: "5610-post-8",
            content: "<p>The Redux store should be in <code>app/store</code> at the root level so it can be shared across all courses. This follows the standard Next.js/Redux pattern.</p>",
            author: "674e52d09a4e696e37024890",
            authorRole: "FACULTY",
            authorName: "Prof. Jose Annunziato",
            createdAt: "2025-01-11T13:40:00"
        },
        {
            _id: "answer-5610-6",
            postId: "5610-post-9",
            content: "<p>Yes, use plural nouns: <code>/api/courses</code> for all courses and <code>/api/courses/:id</code> for a specific course. This is RESTful convention.</p>",
            author: "674e52d09a4e696e37024893",
            authorRole: "TA",
            authorName: "Pramod Kumar",
            createdAt: "2025-01-12T10:45:00"
        },
        {
            _id: "answer-5610-7",
            postId: "5610-post-9",
            content: "<p>Also consider using <code>/api/courses/:courseId/modules</code> for nested resources. It clearly shows the hierarchy.</p>",
            author: "student11",
            authorRole: "STUDENT",
            authorName: "Laura Martinez",
            createdAt: "2025-01-12T11:12:00"
        },
        {
            _id: "answer-5610-8",
            postId: "5610-post-11",
            content: "<p>Use Bootstrap grid for this assignment since we're focusing on Bootstrap components. Save CSS Grid for when you need more complex layouts.</p>",
            author: "674e52d09a4e696e37024890",
            authorRole: "FACULTY",
            authorName: "Prof. Jose Annunziato",
            createdAt: "2025-01-13T10:02:00"
        },
        {
            _id: "answer-5610-9",
            postId: "5610-post-12",
            content: "<p>NextAuth is fine but we haven't covered it in class. Session-based auth would be safer for the assignment to ensure you get full credit.</p>",
            author: "student10",
            authorRole: "STUDENT",
            authorName: "Kelly Anderson",
            createdAt: "2025-01-13T14:20:00"
        },

        // More answers for other courses...
        {
            _id: "answer-5520-1",
            postId: "5520-post-1",
            content: "<p>Please stick with React Native as that's what we're covering in the course. The skills will transfer to other frameworks later.</p>",
            author: "instructor2",
            authorRole: "FACULTY",
            authorName: "Dr. Mike Johnson",
            createdAt: "2025-01-10T11:45:00"
        },
        {
            _id: "answer-5520-2",
            postId: "5520-post-2",
            content: "<p>You need to add camera permissions to your app.json file. Check the Expo documentation for NSCameraUsageDescription.</p>",
            author: "student10",
            authorRole: "STUDENT",
            authorName: "Kelly Anderson",
            createdAt: "2025-01-09T16:00:00"
        },
        {
            _id: "answer-5004-1",
            postId: "5004-post-1",
            content: "<p>Composition means 'part-of' relationship where the part cannot exist without the whole. Aggregation means 'has-a' relationship where parts can exist independently. Think of a House-Room (composition) vs Library-Book (aggregation).</p>",
            author: "instructor3",
            authorRole: "FACULTY",
            authorName: "Dr. Sarah Chen",
            createdAt: "2025-01-10T14:30:00"
        }
    ],

    // Enriched followups collection (4-5 per course)
    followups: [
        // CS5610 followups
        {
            _id: "followup-5610-1",
            postId: "5610-post-2",
            content: "Should we create a tag for each assignment submission?",
            author: "student11",
            authorRole: "STUDENT",
            authorName: "Laura Martinez",
            parentId: null,
            isResolved: false,
            createdAt: "2025-01-10T18:00:00"
        },
        {
            _id: "followup-5610-2",
            postId: "5610-post-2",
            content: "Yes, always tag your submissions! Use tags like 'hw1-submission', 'hw2-submission', etc.",
            author: "674e52d09a4e696e37024893",
            authorRole: "TA",
            authorName: "Pramod Kumar",
            parentId: "followup-5610-1",
            isResolved: true,
            createdAt: "2025-01-10T18:30:00"
        },
        {
            _id: "followup-5610-3",
            postId: "5610-post-3",
            content: "Thanks for the clarification! This makes sense now.",
            author: "student2",
            authorRole: "STUDENT",
            authorName: "Bob Smith",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-08T15:00:00"
        },
        {
            _id: "followup-5610-4",
            postId: "5610-post-4",
            content: "Can you provide a code example for the flexbox solution?",
            author: "student3",
            authorRole: "STUDENT",
            authorName: "Carol Davis",
            parentId: null,
            isResolved: false,
            createdAt: "2025-01-09T17:00:00"
        },
        {
            _id: "followup-5610-5",
            postId: "5610-post-8",
            content: "What about Redux Toolkit Query? Should that also go in app/store?",
            author: "student38",
            authorRole: "STUDENT",
            authorName: "Daniel Kim",
            parentId: null,
            isResolved: false,
            createdAt: "2025-01-11T14:00:00"
        },

        // CS5520 followups
        {
            _id: "followup-5520-1",
            postId: "5520-post-1",
            content: "But Flutter has better performance for complex animations. Can we at least use it for bonus points?",
            author: "student5",
            authorRole: "STUDENT",
            authorName: "Frank Martinez",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-10T12:00:00"
        },
        {
            _id: "followup-5520-2",
            postId: "5520-post-2",
            content: "Did you add the permission to the infoPlist in app.json?",
            author: "student39",
            authorRole: "STUDENT",
            authorName: "Emily Davis",
            parentId: null,
            isResolved: false,
            createdAt: "2025-01-09T16:15:00"
        },
        {
            _id: "followup-5520-3",
            postId: "5520-post-6",
            content: "Both are fine for HW1, but using both shows better understanding of navigation patterns.",
            author: "instructor2",
            authorRole: "FACULTY",
            authorName: "Dr. Mike Johnson",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-12T10:12:00"
        },
        {
            _id: "followup-5520-4",
            postId: "5520-post-8",
            content: "The free tier gives you 1000 notifications per month. Should be plenty for testing!",
            author: "student40",
            authorRole: "STUDENT",
            authorName: "Felix Wong",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-13T12:55:00"
        },
        {
            _id: "followup-5520-5",
            postId: "5520-post-11",
            content: "Always use SecureStore for sensitive data like API keys. AsyncStorage is not encrypted.",
            author: "instructor2",
            authorRole: "FACULTY",
            authorName: "Dr. Mike Johnson",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-15T11:00:00"
        },

        // CS5004 followups
        {
            _id: "followup-5004-1",
            postId: "5004-post-1",
            content: "What about Library and Book? Is that aggregation?",
            author: "student7",
            authorRole: "STUDENT",
            authorName: "Helen Brown",
            parentId: null,
            isResolved: false,
            createdAt: "2025-01-10T15:00:00"
        },
        {
            _id: "followup-5004-2",
            postId: "5004-post-1",
            content: "Yes, Library-Book is aggregation because books can exist without the library.",
            author: "instructor3",
            authorRole: "FACULTY",
            authorName: "Dr. Sarah Chen",
            parentId: "followup-5004-1",
            isResolved: true,
            createdAt: "2025-01-10T15:15:00"
        },
        {
            _id: "followup-5004-3",
            postId: "5004-post-3",
            content: "Use interfaces when you need multiple inheritance. Use abstract classes when you have shared implementation.",
            author: "instructor3",
            authorRole: "FACULTY",
            authorName: "Dr. Sarah Chen",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-11T11:45:00"
        },
        {
            _id: "followup-5004-4",
            postId: "5004-post-7",
            content: "Library system is perfect scope! Focus on core features: checkout, returns, and holds.",
            author: "instructor3",
            authorRole: "FACULTY",
            authorName: "Dr. Sarah Chen",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-13T09:45:00"
        },

        // CS5200 followups
        {
            _id: "followup-5200-1",
            postId: "5200-post-2",
            content: "Primary key cannot be NULL and there's only one per table. UNIQUE can be NULL and you can have multiple.",
            author: "instructor4",
            authorRole: "FACULTY",
            authorName: "Dr. Lina Gomez",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-08T12:05:00"
        },
        {
            _id: "followup-5200-2",
            postId: "5200-post-3",
            content: "Join tables are the standard approach. They're flexible and maintain referential integrity.",
            author: "instructor4",
            authorRole: "FACULTY",
            authorName: "Dr. Lina Gomez",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-09T10:40:00"
        },
        {
            _id: "followup-5200-3",
            postId: "5200-post-3",
            content: "You can also use arrays in PostgreSQL for simple many-to-many, but join tables are cleaner.",
            author: "student41",
            authorRole: "STUDENT",
            authorName: "Gary Chen",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-09T10:50:00"
        },
        {
            _id: "followup-5200-4",
            postId: "5200-post-8",
            content: "Start with composite indexes on your WHERE clause columns. Partitioning is overkill for 1M rows.",
            author: "instructor4",
            authorRole: "FACULTY",
            authorName: "Dr. Lina Gomez",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-14T11:30:00"
        },
        {
            _id: "followup-5200-5",
            postId: "5200-post-8",
            content: "Also check EXPLAIN ANALYZE to see your query plan. Often the issue is missing statistics.",
            author: "student42",
            authorRole: "STUDENT",
            authorName: "Hannah Lee",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-14T11:45:00"
        },

        // CS5800 followups
        {
            _id: "followup-5800-1",
            postId: "5800-post-2",
            content: "Use induction for recursive algorithms. Use loop invariants for iterative algorithms.",
            author: "instructor5",
            authorRole: "FACULTY",
            authorName: "Dr. Ethan Brooks",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-08T14:50:00"
        },
        {
            _id: "followup-5800-2",
            postId: "5800-post-2",
            content: "Sometimes you can use both! Choose the one that makes the proof cleaner.",
            author: "student43",
            authorRole: "STUDENT",
            authorName: "Isaac Park",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-08T15:05:00"
        },
        {
            _id: "followup-5800-3",
            postId: "5800-post-6",
            content: "Dijkstra fails with negative edges because it assumes shortest paths are final when visited.",
            author: "instructor5",
            authorRole: "FACULTY",
            authorName: "Dr. Ethan Brooks",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-12T10:55:00"
        },
        {
            _id: "followup-5800-4",
            postId: "5800-post-6",
            content: "Try this example: Graph with edges A→B(1), B→C(1), A→C(3), C→B(-2). Dijkstra gives wrong answer.",
            author: "student44",
            authorRole: "STUDENT",
            authorName: "Julia Martinez",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-12T11:05:00"
        },
        {
            _id: "followup-5800-5",
            postId: "5800-post-9",
            content: "Reduce FROM known NP-complete TO your problem X. Think: 'If I can solve X, I can solve the known hard problem.'",
            author: "instructor5",
            authorRole: "FACULTY",
            authorName: "Dr. Ethan Brooks",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-14T14:00:00"
        },

        // CS6510 followups
        {
            _id: "followup-6510-1",
            postId: "6510-post-2",
            content: "Yes, follow the Clean Architecture naming conventions strictly. Points will be deducted for inconsistency.",
            author: "instructor6",
            authorRole: "FACULTY",
            authorName: "Dr. Olivia Reed",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-08T12:40:00"
        },
        {
            _id: "followup-6510-2",
            postId: "6510-post-3",
            content: "Monorepo with Nx gives better code sharing. We use it at my internship and it's great!",
            author: "student45",
            authorRole: "STUDENT",
            authorName: "Kyle Thompson",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-09T09:55:00"
        },
        {
            _id: "followup-6510-3",
            postId: "6510-post-6",
            content: "Use environment variables for feature flags locally. LaunchDarkly has a free tier too.",
            author: "instructor6",
            authorRole: "FACULTY",
            authorName: "Dr. Olivia Reed",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-12T13:55:00"
        },
        {
            _id: "followup-6510-4",
            postId: "6510-post-6",
            content: "I built a simple feature flag service with Redis. Happy to share the code!",
            author: "student46",
            authorRole: "STUDENT",
            authorName: "Liam Wilson",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-12T14:05:00"
        },

        // CS6620 followups
        {
            _id: "followup-6620-1",
            postId: "6620-post-2",
            content: "Attach policies to roles, then assign roles to resources. Never attach policies directly to users in production.",
            author: "instructor7",
            authorRole: "FACULTY",
            authorName: "Dr. Victor Huang",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-08T13:20:00"
        },
        {
            _id: "followup-6620-2",
            postId: "6620-post-3",
            content: "Use CloudFront invalidations sparingly—they cost money. Set proper cache headers instead.",
            author: "instructor7",
            authorRole: "FACULTY",
            authorName: "Dr. Victor Huang",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-09T10:55:00"
        },
        {
            _id: "followup-6620-3",
            postId: "6620-post-3",
            content: "You can also use versioned file names (like app.v2.js) to avoid invalidation needs.",
            author: "student47",
            authorRole: "STUDENT",
            authorName: "Monica Zhang",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-09T11:05:00"
        },
        {
            _id: "followup-6620-4",
            postId: "6620-post-6",
            content: "VPC peering is simpler and cheaper for HW3. Save Transit Gateway for multi-region setups.",
            author: "instructor7",
            authorRole: "FACULTY",
            authorName: "Dr. Victor Huang",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-12T10:15:00"
        },
        {
            _id: "followup-6620-5",
            postId: "6620-post-9",
            content: "RDS Proxy works great with Lambda! It manages connection pooling which DynamoDB doesn't need.",
            author: "student48",
            authorRole: "STUDENT",
            authorName: "Nathan Brown",
            parentId: null,
            isResolved: true,
            createdAt: "2025-01-14T15:30:00"
        }
    ]
};

export { pazzaSeedData };