export default [
    {
        "_id": "Q5004-01",
        "course": "5004",
        "category": "Quizzes",
        "title": "Learning Activity: Classes & Objects",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5004-02",
        "course": "5004",
        "category": "Quizzes",
        "title": "Learning Activity: Inheritance & Polymorphism",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5004-03",
        "course": "5004",
        "category": "Quizzes",
        "title": "Learning Activity: SOLID Principles",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5004-04",
        "course": "5004",
        "category": "Quizzes",
        "title": "Learning Activity: Design Patterns - Creational",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5004-05",
        "course": "5004",
        "category": "Quizzes",
        "title": "Learning Activity: Design Patterns - Structural",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5004-06",
        "course": "5004",
        "category": "Quizzes",
        "title": "Learning Activity: Design Patterns - Behavioral",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5004-07",
        "course": "5004",
        "category": "Quizzes",
        "title": "Learning Activity: UML Diagrams",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5004-08",
        "course": "5004",
        "category": "Exams",
        "title": "Midterm Exam",
        "points": 100,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 25
    },
    {
        "_id": "Q5100-01",
        "course": "5100",
        "category": "Quizzes",
        "title": "Learning Activity: Uninformed Search",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5100-02",
        "course": "5100",
        "category": "Quizzes",
        "title": "Learning Activity: Informed Search & A*",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5100-03",
        "course": "5100",
        "category": "Quizzes",
        "title": "Learning Activity: Adversarial Search",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5100-04",
        "course": "5100",
        "category": "Quizzes",
        "title": "Learning Activity: Constraint Satisfaction",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5100-05",
        "course": "5100",
        "category": "Quizzes",
        "title": "Learning Activity: Markov Decision Processes",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5100-06",
        "course": "5100",
        "category": "Exams",
        "title": "Midterm Exam",
        "points": 100,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 25
    },
    {
        "_id": "Q5100-07",
        "course": "5100",
        "category": "Quizzes",
        "title": "Learning Activity: Reinforcement Learning",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5100-08",
        "course": "5100",
        "category": "Quizzes",
        "title": "Learning Activity: Logic & Inference",
        "points": 20,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5200-01",
        "course": "5200",
        "category": "Quizzes",
        "title": "Learning Activity: Relational Model & SQL Basics",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5200-02",
        "course": "5200",
        "category": "Quizzes",
        "title": "Learning Activity: Joins & Subqueries",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5200-03",
        "course": "5200",
        "category": "Quizzes",
        "title": "Learning Activity: Normalization & ER Diagrams",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5200-04",
        "course": "5200",
        "category": "Quizzes",
        "title": "Learning Activity: Indexes & Query Optimization",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5200-05",
        "course": "5200",
        "category": "Quizzes",
        "title": "Learning Activity: Transactions & ACID",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5200-06",
        "course": "5200",
        "category": "Quizzes",
        "title": "Learning Activity: Stored Procedures & Triggers",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5200-07",
        "course": "5200",
        "category": "Quizzes",
        "title": "Learning Activity: NoSQL & MongoDB",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5200-08",
        "course": "5200",
        "category": "Quizzes",
        "title": "Database Design Project",
        "points": 20,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5520-01",
        "course": "5520",
        "category": "Quizzes",
        "title": "Learning Activity: Mobile UI Basics",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5520-02",
        "course": "5520",
        "category": "Quizzes",
        "title": "Learning Activity: Navigation & Routing",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5520-03",
        "course": "5520",
        "category": "Quizzes",
        "title": "Learning Activity: State Management",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5520-04",
        "course": "5520",
        "category": "Quizzes",
        "title": "Learning Activity: Networking & API Integration",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5520-05",
        "course": "5520",
        "category": "Quizzes",
        "title": "Learning Activity: Local Storage & Persistence",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5520-06",
        "course": "5520",
        "category": "Quizzes",
        "title": "Learning Activity: Device APIs & Sensors",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5520-07",
        "course": "5520",
        "category": "Quizzes",
        "title": "Learning Activity: Push Notifications",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5520-08",
        "course": "5520",
        "category": "Exams",
        "title": "Final Project Presentation",
        "points": 100,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 25
    },
    {
        "_id": "Q5610-01",
        "course": "5610",
        "category": "Quizzes",
        "title": "Learning Activity: HTML & Semantic Markup",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5610-02",
        "course": "5610",
        "category": "Quizzes",
        "title": "Learning Activity: CSS Flexbox & Grid",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5610-03",
        "course": "5610",
        "category": "Quizzes",
        "title": "Learning Activity: JavaScript DOM Manipulation",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5610-04",
        "course": "5610",
        "category": "Quizzes",
        "title": "Learning Activity: React Components & Props",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5610-05",
        "course": "5610",
        "category": "Quizzes",
        "title": "Learning Activity: State Management & Hooks",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5610-06",
        "course": "5610",
        "category": "Quizzes",
        "title": "Learning Activity: REST APIs & Fetch",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5610-07",
        "course": "5610",
        "category": "Exams",
        "title": "Midterm Exam",
        "points": 100,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 25
    },
    {
        "_id": "Q5610-08",
        "course": "5610",
        "category": "Quizzes",
        "title": "Learning Activity: MongoDB & NoSQL",
        "points": 20,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5700-01",
        "course": "5700",
        "category": "Quizzes",
        "title": "Learning Activity: Protocol Layering & TCP/IP",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5700-02",
        "course": "5700",
        "category": "Quizzes",
        "title": "Learning Activity: Socket Programming",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5700-03",
        "course": "5700",
        "category": "Quizzes",
        "title": "Learning Activity: Reliable Data Transfer",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5700-04",
        "course": "5700",
        "category": "Quizzes",
        "title": "Learning Activity: TCP Congestion Control",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5700-05",
        "course": "5700",
        "category": "Quizzes",
        "title": "Learning Activity: Routing & Forwarding",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5700-06",
        "course": "5700",
        "category": "Exams",
        "title": "Midterm Exam",
        "points": 100,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 25
    },
    {
        "_id": "Q5700-07",
        "course": "5700",
        "category": "Quizzes",
        "title": "Learning Activity: DNS, HTTP & Applications",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5700-08",
        "course": "5700",
        "category": "Quizzes",
        "title": "Learning Activity: Network Security & TLS",
        "points": 20,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5800-01",
        "course": "5800",
        "category": "Quizzes",
        "title": "Learning Activity: Big O Notation & Analysis",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5800-02",
        "course": "5800",
        "category": "Quizzes",
        "title": "Learning Activity: Sorting Algorithms",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5800-03",
        "course": "5800",
        "category": "Quizzes",
        "title": "Learning Activity: Trees & Heaps",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5800-04",
        "course": "5800",
        "category": "Quizzes",
        "title": "Learning Activity: Graphs & Traversals",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5800-05",
        "course": "5800",
        "category": "Quizzes",
        "title": "Learning Activity: Dynamic Programming",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5800-06",
        "course": "5800",
        "category": "Quizzes",
        "title": "Learning Activity: Greedy Algorithms",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5800-07",
        "course": "5800",
        "category": "Quizzes",
        "title": "Learning Activity: Divide & Conquer",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q5800-08",
        "course": "5800",
        "category": "Exams",
        "title": "Midterm Exam",
        "points": 100,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 25
    },
    {
        "_id": "Q6140-01",
        "course": "6140",
        "category": "Quizzes",
        "title": "Learning Activity: Linear Regression",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6140-02",
        "course": "6140",
        "category": "Quizzes",
        "title": "Learning Activity: Logistic Regression",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6140-03",
        "course": "6140",
        "category": "Quizzes",
        "title": "Learning Activity: Decision Trees & Naive Bayes",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6140-04",
        "course": "6140",
        "category": "Quizzes",
        "title": "Learning Activity: SVMs & Kernels",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6140-05",
        "course": "6140",
        "category": "Quizzes",
        "title": "Learning Activity: Neural Networks",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6140-06",
        "course": "6140",
        "category": "Exams",
        "title": "Midterm Exam",
        "points": 100,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 25
    },
    {
        "_id": "Q6140-07",
        "course": "6140",
        "category": "Quizzes",
        "title": "Learning Activity: Clustering & PCA",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6140-08",
        "course": "6140",
        "category": "Quizzes",
        "title": "Learning Activity: Model Evaluation",
        "points": 20,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6510-01",
        "course": "6510",
        "category": "Quizzes",
        "title": "Learning Activity: Agile Methodologies",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6510-02",
        "course": "6510",
        "category": "Quizzes",
        "title": "Learning Activity: Software Architecture",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6510-03",
        "course": "6510",
        "category": "Quizzes",
        "title": "Learning Activity: Microservices",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6510-04",
        "course": "6510",
        "category": "Quizzes",
        "title": "Learning Activity: Testing Strategies",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6510-05",
        "course": "6510",
        "category": "Quizzes",
        "title": "Learning Activity: Code Quality & Reviews",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6510-06",
        "course": "6510",
        "category": "Quizzes",
        "title": "Learning Activity: DevOps Practices",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6510-07",
        "course": "6510",
        "category": "Quizzes",
        "title": "Learning Activity: Performance Optimization",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6510-08",
        "course": "6510",
        "category": "Quizzes",
        "title": "Team Project Presentation",
        "points": 20,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6620-01",
        "course": "6620",
        "category": "Quizzes",
        "title": "Learning Activity: Cloud Computing Basics",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6620-02",
        "course": "6620",
        "category": "Quizzes",
        "title": "Learning Activity: Virtualization & Containers",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6620-03",
        "course": "6620",
        "category": "Quizzes",
        "title": "Learning Activity: Docker & Kubernetes",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6620-04",
        "course": "6620",
        "category": "Quizzes",
        "title": "Learning Activity: AWS Services",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6620-05",
        "course": "6620",
        "category": "Quizzes",
        "title": "Learning Activity: Serverless Architecture",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6620-06",
        "course": "6620",
        "category": "Quizzes",
        "title": "Learning Activity: Cloud Security",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6620-07",
        "course": "6620",
        "category": "Quizzes",
        "title": "Learning Activity: CI/CD Pipelines",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6620-08",
        "course": "6620",
        "category": "Quizzes",
        "title": "Cloud Architecture Project",
        "points": 20,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6650-01",
        "course": "6650",
        "category": "Quizzes",
        "title": "Learning Activity: Threads & Synchronization",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-15",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6650-02",
        "course": "6650",
        "category": "Quizzes",
        "title": "Learning Activity: Sockets & RPC",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-22",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6650-03",
        "course": "6650",
        "category": "Quizzes",
        "title": "Learning Activity: Consistency Models",
        "points": 20,
        "score": null,
        "dueDate": "2025-09-29",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6650-04",
        "course": "6650",
        "category": "Quizzes",
        "title": "Learning Activity: Consensus & Paxos",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-06",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6650-05",
        "course": "6650",
        "category": "Quizzes",
        "title": "Learning Activity: Message Queues",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-13",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6650-06",
        "course": "6650",
        "category": "Exams",
        "title": "Midterm Exam",
        "points": 100,
        "score": null,
        "dueDate": "2025-10-20",
        "status": "Not Started",
        "questions": 25
    },
    {
        "_id": "Q6650-07",
        "course": "6650",
        "category": "Quizzes",
        "title": "Learning Activity: Microservices",
        "points": 20,
        "score": null,
        "dueDate": "2025-10-27",
        "status": "Not Started",
        "questions": 10
    },
    {
        "_id": "Q6650-08",
        "course": "6650",
        "category": "Quizzes",
        "title": "Learning Activity: Cloud Scaling & Load Balancing",
        "points": 20,
        "score": null,
        "dueDate": "2025-11-03",
        "status": "Not Started",
        "questions": 10
    }
];
